#!/bin/bash

mkdir -p $REPOSITORY_ROOT
while read repo; do
	echo "mirroring $repo"
	if [[ ! -e $repo ]]; then
		git clone --mirror $repo $REPOSITORY_ROOT/$(basename $repo)
	fi
done < ${WORKSPACE}/project/external-projects

